version: '3'
services:
  web:
    image: "kindlebit143/weclea-backend:v2.0"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    networks:
      - mynetwork
  #  volumes:
  #    - web-data:/app/data  # Mount a named volume for the web service

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql  # Mount a named volume for the MySQL service
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
#  web-data:  # Define a named volume for the web service
  mysql-data:  # Define a named volume for the MySQL service
