version: "3"
services:
  app:
    image: "kindlebit143/weclea_backend:v0.2"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - MAX_FILE_SIZE=500mb 
      - max_execution_time = 300
      - post_max_size=50M
      - upload_max_filesize=50M
    networks:
      - myconnection
    volumes:
      - /home/ubuntu/uploads:/app/uploads

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_BIND_ADDRESS: "0.0.0.0"
    volumes:
     - db_backup:/var/lib/mysql  # Define the volume for MySQL data #db pass change
    networks:
      - myconnection

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 500M
    depends_on:
      - mysql
    networks:
      - myconnection

networks:
  myconnection:
    driver: bridge

# Define volumes
volumes:
  db_backup:  # Define the MySQL data volume
