version: "3"
services:
  app:
    image: "kindlebit143/weclea_backend:v0.2"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    networks:
      - myconnection
    volumes:
      - /home/ubuntu/uploads:/app/uploads

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_BIND_ADDRESS: "0.0.0.0"
    volumes:
     - db_backup:/var/lib/mysql  # Define the volume for MySQL data
    networks:
      - myconnection

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - myconnection

networks:
  myconnection:
    driver: bridge

# Define volumes
volumes:
  db_backup:  # Define the MySQL data volume
