name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner label here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env file
        run: |
          cp -r /home/ubuntu/uploads /var/weclea/weclea_backend/weclea-backend/weclea-backend/weclea-backend

      - name: Copy .env file
        run: |
          cp /home/ubuntu/.env /var/weclea/weclea_backend/weclea-backend/weclea-backend/weclea-backend

      - name: Build and Test
        run: |
          docker build . -t kindlebit143/weclea_backend:v0.2
      
      - name: Login to DockerHub
        run: |
          echo 'Pushing code to DockerHub'
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push kindlebit143/weclea_backend:v0.2  

      - name: Deploy on server
        run: |
          # Perform cleanup steps here (e.g., deleting temporary files)
          docker-compose down
          docker-compose up -d
          # Add your cleanup commands here
