name: production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: weclea-backend  # Use your self-hosted runner label here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        env:
          GIT_MAX_INPUT: 10000000 # Set a larger value for maxBuffer (in bytes)

      # - name: Copy uploads folder // don't uncommit it 
      #   run: |
      #     cp -r /home/ubuntu/uploads /var/weclea/weclea_backend/weclea-backend/weclea-backend/weclea-backend

      - name: Copy .env file
        run: |
          cp /home/ubuntu/.env /var/weclea/weclea_backend/weclea-backend/weclea-backend/weclea-backend

      - name: Build and Test
        run: |
          docker build . -t kindlebit143/weclea_backend:v0.2

      # - name: Login to DockerHub
      #   run: |
      #     echo 'Pushing code to DockerHub'
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker push kindlebit143/weclea_backend:v0.2

      - name: Deploy on server
        run: |
          # Perform cleanup steps here (e.g., deleting temporary files)
          #docker-compose down
          #docker-compose up -d
          docker-compose stop app
          docker-compose up -d app
          # Add your cleanup commands heree
          #docker system prune -af
