name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker build . -t kindlebit143/weclea_backend:v0.1

      - name: Login to DockerHub
        run: |
          echo 'Pushing code to DockerHub'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push kindlebit143/weclea_backend:v0.1

  deploy:
    runs-on: self-hosted  # Use your self-hosted runner label here
    needs: build  # Indicates that this job depends on the 'build' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on server
        run: |
          # Load secrets from GitHub Secrets into environment variables
          export PORT=3000
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export HTTPURL=${{ secrets.HTTPURL }}
          export DB_DATABASE=${{ secrets.DB_DATABASE }}
          export ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}"
          export STRIPE_PUBLISH_KEY="${{ secrets.STRIPE_PUBLISH_KEY }}"
          export STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}"
          
          # Example: Deploy using Docker Compose
          docker-compose down
          docker-compose up -d
